config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end


  def show
  end

  def new
   @task = Task.new
 end

 def create
  @task = Task.new(task_params)
  @task.save
  redirect_to tasks_path
end

def edit
end

def update
 @task.update(task_params)
 redirect_to tasks_path
end

def destroy
  @task.destroy
  redirect_to tasks_path
end

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:name, :done)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.check_box :done %>
<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
<h2><%= task.name %></h2>
<p><%= task.done %></p>
<%= link_to "More Details", task_path(task) %>
<%= link_to "Edit", edit_task_path(task) %>
<%= link_to "Delete", task_path(task), method: :delete %>


<br>========================================

<% end %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.done %></p>
<p><%= @task.created_at %></p>

<%= link_to "Edit", edit_task_path(@task) %>
<%= link_to "Destroy", task_path(@task), method: :delete %>